### ISSUE TITLE
Dispose error on unitialized control

### ISSUE THREAD

**Issue by MikaelStalvik** [opentk/GLWpfControl#113]
If the GLWpfControl cannot be initialized as described in [this issue](https://github.com/opentk/GLWpfControl/issues/112), an error will be thrown when the control is internally disposed:

`OpenTK.Windowing.GraphicsLibraryFramework.GLFWException: You can only dispose windows on the main thread. The window needs to be disposed as it cannot safely be disposed in the finalizer.
at OpenTK.Windowing.Desktop.NativeWindow.Dispose(System.Boolean disposing) at offset 54
at OpenTK.Windowing.Desktop.NativeWindow.Finalize()`

This seems weird since the actual control is created, but not properly initialized, on the main thread.

**Comment by NogginBops** [comment]
Ok it seems like this is happening because after the exception is thrown in window creation the `NativeWindow` finalizer gets called and that isn't supposed to happen.
Not sure if this issue is best fixed in GLWpfControl or in OpenTK itself, will have to think about that one.
But basically we could catch the exception and dispose the window ourself in some way, but it might require changes in OpenTK to fully work.
