### ISSUE TITLE
OpenTkControl_OnRender not  being called 

### ISSUE THREAD

**Issue by ping11700** [opentk/GLWpfControl#147]
``
<Window>
  <glWpfControl:GLWpfControl x:Name="OpenTkControl" Render="OpenTkControl_OnRender" />
</Window>
``

OpenTkControl in wpf window,  OnRender not  being  called while dragMove that window.

**Comment by NogginBops** [comment]
Do any other controls paint dynamically while the window is moving?

This is a limitation in windows that makes it pretty hard to deal with repainting windows while they are moving. If regular WPF controls support drawing while the window is moving we can try and support that too, but otherwise we are aiming to do what most WPF controls do.

**Comment by ping11700** [comment]
wpf window not call OnRender while being dragmoved,  what should we do that video in OpenTkControl cant render with the window's moving.

**Comment by ping11700** [comment]
wpf window not call OnRender while being dragmoved,  what should we do that video in OpenTkControl cant render with the window's moving.

**Comment by NogginBops** [comment]
Did you figure out a solution to playing video in a moving window?
One decently simple solution would be to temporarily pause the video while the window is moving, which might be an ok user experience.

You could also try to update the window contents, but I'm not sure how you get wpf to trigger a repaint while the window is moving. But maybe it's possible with `Invalidate` or something.

**Comment by ping11700** [comment]
thank you for your reply, i just create a new video window to deal with it.
