### ISSUE TITLE
Provide access to current graphics context

### ISSUE THREAD

**Issue by cwensley** [opentk/GLWpfControl#43]
There's currently no way to get the IGraphicsContext that gets created from the control.

I realize there's the ability to pass a custom context via `GLWpfControlSettings.ContextToUse`, however it would be nice to be able to get the shared one created automatically without having to do it manually.

**Comment by varon** [comment]
Accessing the graphics context is considered pretty advanced stuff, so it's expected that you go around the manual way of doing things then.

A ton of other issues arise too with exposing the context, because now our reference counter isn't working etc.

Unfortunately, this isn't something we can address directly.
