### ISSUE TITLE
Flickering when low framerate?

### ISSUE THREAD

**Issue by migeyusu** [opentk/GLWpfControl#50]
Hi team, default sample in the repos works well, but it' on high framerate which is 60. When I render lot's of objects in the control , flickering occured, i think the source the problem maybee d3dimage . I've grope for solution to prevent flicker on d3dimage but failed. Can anyone help me?

**Comment by romen-h** [comment]
I could repeat this issue too, but it was due to slow texture uploads making the framerate about ~20 FPS. (For a camera)
Due to the way I needed to use the control, I just disabled `RenderContinuously` and called `InvalidateVisual()` after each new texture was completely uploaded. The flicker seems to be gone now because it only renders when told to.

I think the flicker was some kind of race condition.

**Comment by migeyusu** [comment]
> I could repeat this issue too, but it was due to slow texture uploads making the framerate about ~20 FPS. (For a camera)
> Due to the way I needed to use the control, I just disabled `RenderContinuously` and called `InvalidateVisual()` after each new texture was completely uploaded. The flicker seems to be gone now because it only renders when told to.
> 
> I think the flicker was some kind of race condition.

![image](https://user-images.githubusercontent.com/29461339/125784022-884fbb75-a9ec-4a18-a651-ada6037fecce.png)
I discovered the root of the problem: there should be GL.Finish() but not GL.Flush()!  The problem is sync.

**Comment by migeyusu** [comment]
Well,  I contend that create a standlone  and high priority thread to render and sync to OnRender lest GL.Finish wont block the ui thread.
