### ISSUE TITLE
.Net framework application crashes with System.StackOverflowException: 'Exception_WasThrown'

### ISSUE THREAD

**Issue by xhuan8** [opentk/GLWpfControl#84]
Hi,

I have .net framework 6.0 and GLWpfControl 4.2.2

I put GLWpfControl  in a sub window, it works good for the first show the sub window, but when open the sub window for the second time, press the arrow keys (actually any key) will case System.StackOverflowException: 'Exception_WasThrown'

but there is no stack trace, and not event logs.
I believe something must be cleared on window closing, any advise?

```
public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
        }

        private void button_Click(object sender, RoutedEventArgs e)
        {
            Window1 dialog = new Window1();
            dialog.ShowDialog();
        }
    }
```

```
public partial class Window1 : Window
    {
        public Window1()
        {
            InitializeComponent();

            var settings = new GLWpfControlSettings
            {
                MajorVersion = 2,
                MinorVersion = 1
            };
            OpenTkControl.Start(settings);

            //GL.Enable(EnableCap.Blend);
            GL.Enable(EnableCap.DepthTest);
            //GL.Enable(EnableCap.ScissorTest);
        }
}
```

**Comment by xhuan8** [comment]
duplicate with #82

**Comment by NogginBops** [comment]
For future reference, you are using ".net 6". ".net framework" is the name used to refer to the closed source windows framework, while ".net core" (for versions <5) and ".net" (for versions >=5) are the new names for the open source cross platform frameworks.

It's pretty confusing, but it's important because ".net framework 6" (which people could think to mean 4.6) and ".net 6" are two completely different things that where released 6 years apart.
