### ISSUE TITLE
How to correct release resources?

### ISSUE THREAD

**Issue by MingGuys** [opentk/GLWpfControl#96]
I release resouces like 
~~~
            GL.BindBuffer(BufferTarget.ArrayBuffer, 0);
            GL.BindVertexArray(0);
            GL.UseProgram(0);

            // Delete all the resources.
            GL.DeleteBuffer(VBO);
            GL.DeleteVertexArray(VAO);
            GL.DeleteBuffer(EBO);

            GL.DeleteProgram(ActiveShader.Handle);
~~~
But this won't work.Everytime reopen the window that contains GLWpfControl.I got this exception:
"An unhandled exception of type 'System.ExecutionEngineException' occurred in OpenTK.Graphics.dll".

**Comment by NogginBops** [comment]
I think this issue is not because of how you release your resources. `ExecutionEngineException` means that something went wrong in the runtime itself, this can happen if there are missmatched versions of assemblies used or if the process is running in 32-bit mode but has some code that doesn't work in 32bit mode.

**Comment by NogginBops** [comment]
Closing as there are no updates.
